plugins {
    id 'com.android.application'
}

android {
    namespace 'com.anonymouskeys.xdns'
    compileSdk 34

    defaultConfig {
        applicationId "com.anonymouskeys.xdns"
        minSdk 26
        targetSdk 34
        versionCode 15
        versionName "0.7.0-control"
    }

    signingConfigs {
        debug {
            storeFile rootProject.file("debug-signing/xdns-debug.keystore")
            storePassword "android"
            keyAlias "androiddebugkey"
            keyPassword "android"
        }
    }

    buildTypes {
        debug {
            applicationIdSuffix ".debug"
            versionNameSuffix "-debug"
            signingConfig signingConfigs.debug
            manifestPlaceholders = [appLabel: "X-dns Debug"]
        }
        release {
            manifestPlaceholders = [appLabel: "X-dns"]
        }
    }

    compileOptions {
        sourceCompatibility JavaVersion.VERSION_17
        targetCompatibility JavaVersion.VERSION_17
    }

    packaging {
        jniLibs {
            useLegacyPackaging = true
        }
    }
}

dependencies {
    implementation 'com.squareup.okhttp3:okhttp:4.12.0'
}
